### ISSUE TITLE
Feature Request: Delay paste visibility for up to X

### ISSUE THREAD

**Issue by phil71x** [notrustverify/pastenym-cli#3]
X being a duration, a number of block, a specific time, or block height.

It should be a use case. I just don't know which one!

**Comment by sven-hash** [comment]
Thanks for this

We will add some demo when everything will be ready

**Comment by sven-hash** [comment]
Here's the doc for time expiration, block height will come later

https://github.com/notrustverify/pastenym-cli/blob/main/README.md#create-a-paste-with-time-expiration
